set -g mouse on

setw -g mode-keys vi

# Let programs (vim, etc.) detect when a pane gains/loses focus

set -g focus-events on

# Easier reload

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

# More natural splitting

bind | split-window -h

bind - split-window -v

# Better pane movement with vim-ish keys

bind h select-pane -L

bind j select-pane -D

bind k select-pane -U

bind l select-pane -R
